const projects = [
  {
    name: "Strategy Navigator - AI SaaS Platform",
    year: "2025",
    image: "/images/strategy-navigator.png",
    liveDemo: "https://strategynavigator.ai/",
    role: "Full Stack Web Developer",
    stack: ["React", "Node.js", "OpenAI", "Stripe"],
    impact: "Integrated 65+ AI tools and delivered production RBAC, billing, and collaboration workflows.",
    visibility: "Public Product",
  },
  {
    name: "JourneyAI - AI Sales Assistant Platform",
    year: "2025",
    image: "/images/journeyai.png",
    liveDemo: "https://meetjourney.ai/",
    role: "Full Stack Web Developer",
    stack: ["React", "FastAPI", "OpenAI", "WebSocket"],
    impact: "Built 10+ assistants with real-time chat, speech workflows, meeting prep, and billing.",
    visibility: "Public Product",
  },
  {
    name: "SaleSide AI - Sales Meeting Assistant",
    year: "2025",
    image: "/images/saleside.png",
    liveDemo: "https://saleside.ai/",
    role: "Full Stack Web Developer",
    stack: ["Python", "WebSocket", "OpenAI"],
    impact: "Automated transcription, summaries, objection tracking, and follow-up extraction.",
    visibility: "Public Product",
  },
  {
    name: "RxCare / Deep Analyzer Suite",
    year: "Recent",
    image: "/images/rxcare-suite.svg",
    role: "Full Stack Mobile Developer",
    stack: ["React Native", "Expo", "TypeScript", "Express.js", "OpenAI"],
    impact: "Built a healthcare mobile app for prescriptions, refills, telehealth, lab tracking, family care coordination, and AI pharmacist chat.",
    visibility: "Private Client Project",
  },
  {
    name: "Tunisia Auto Connect / AutoTN",
    year: "Recent",
    image: "/images/autotn-market.svg",
    role: "Full Stack Mobile Developer",
    stack: ["React Native", "Expo", "TypeScript", "Express.js", "PostgreSQL", "OpenAI"],
    impact: "Delivered a trilingual automotive marketplace with AI diagnostics, VIN decoding, valuation workflows, and seller contact features.",
    visibility: "Private Client Project",
  },
  {
    name: "Integrity Solve - AML/CTF Compliance Portal",
    year: "Recent",
    image: "/images/integrity-solve.svg",
    role: "Full Stack Web Developer",
    stack: ["React", "TypeScript", "Express.js", "PostgreSQL"],
    impact: "Built AML and CTF onboarding, risk routing, verification, audit evidence, and case review workflows for compliance teams.",
    visibility: "Private Client Project",
  },
  {
    name: "Job Scraper and Outreach Automation",
    year: "2025",
    image: "/images/website-img-1.jpg",
    role: "Automation and Full Stack Developer",
    stack: ["Python", "Node.js", "OpenAI", "MongoDB"],
    impact: "Scraped jobs from 40+ platforms and automated lead enrichment for outreach workflows.",
    visibility: "Private Client Project",
  },
  {
    name: "Outreach Personalization Engine",
    year: "2025",
    image: "/images/website-img-3.jpg",
    role: "Automation and Full Stack Developer",
    stack: ["Python", "OpenAI", "Node.js"],
    impact: "Generated personalized outreach from company signals and lead context at scale.",
    visibility: "Private Client Project",
  },
  {
    name: "LMS with AI Integration and WebSocket",
    year: "2024",
    image: "/images/lms.PNG",
    liveDemo: "https://e-learning-five-tau.vercel.app",
    role: "Full Stack Developer (Intern)",
    stack: ["React", "Node.js", "MongoDB", "WebSocket"],
    impact: "Built AI chatbot support and real-time learning interactions for an e-learning platform.",
    visibility: "Public Demo",
  },
  {
    name: "E-commerce Dashboard",
    year: "2023",
    image: "/images/dash.PNG",
    liveDemo: "https://dashboard-rho-gray-61.vercel.app/dashboard",
    github: "https://github.com/aymenkhaled/dashboard",
    role: "Full Stack Developer",
    stack: ["React", "Node.js", "PostgreSQL"],
    impact: "Centralized analytics, inventory, and order tracking in one operational dashboard.",
    visibility: "Public Demo",
  },
  {
    name: "SEO Optimization SaaS - Issue Detector",
    year: "2024",
    image: "/images/website-img-2.webp",
    role: "Full Stack Developer",
    stack: ["React", "Node.js", "PostgreSQL"],
    impact: "Automated SEO issue detection and prioritized fixes into a clear action workflow.",
    visibility: "Private Client Project",
  },
];

export default projects;
